### ISSUE TITLE
Test T5-1.1-base performance on SGLUE

### ISSUE THREAD

**Issue by lintangsutawika** [EleutherAI/architecture-objective#20]

**Comment by AranKomat** [comment]
@lintangsutawika I think we probably don't even need to do this given that I don't see anything non-conventional about your implementation of SGLUE. As long as we get reasonable performance by finetuning our existing ckpts relative to the official performance, it should be fine :) That being said, I'll start finetuning and will let you know if the resulting performance is abnormal.

**Comment by AranKomat** [comment]
Since I've observed performance that is reasonable relative to the official T5 SGLUE performance with similar compute budget, I'm closing this issue :)
