### ISSUE TITLE
Check SGLUE Mixture Eval

### ISSUE THREAD

**Issue by lintangsutawika** [EleutherAI/architecture-objective#21]
Check if eval when training on SGLUE Mixture shows accuracy of individual scores as well.

**Comment by lintangsutawika** [comment]
Only shows individual task accuracy. Need to figure out how to get the average.

![Image](https://user-images.githubusercontent.com/5774558/201452231-079db075-5016-4b06-9b5a-893693cc89ff.png)

**Comment by AranKomat** [comment]
I guess we can forget about this, as it's not particularly important :)
