### ISSUE TITLE
Make small deduped Pile

### ISSUE THREAD

**Issue by AranKomat** [EleutherAI/architecture-objective#22]
We need to do memorization experiments (i.e. varying the number of epochs to see the viability of high-epoch training with T5) on deduped Pile, given that large epoch training with C4, which contains some sequences duplicated numerous times, often leads to instability. 

We have 20 jsonl files of deduped Pile, each of which contains about 10B tokens, at `/fsx/pile_raw_deduped/dedupe0.87/train/`. The only task left is to split `00.jsonl` in this directory into 100 equal-sized jsonl's and place at somewhere else, possibly somewhere at `improved-t5`.

**Comment by lintangsutawika** [comment]
This is still unclear to me, what is the purpose and relation of splitting `00.jsonl` to the memorization experiments?

**Comment by haileyschoelkopf** [comment]
Do we know that each of those jsonls for the deduped Pile were shuffled beforehand (would taking only 00.jsonl be a representative sample of the deduped Pile?)

**Comment by AranKomat** [comment]
@lintangsutawika Unlike C4, which is split into 1024 files, each of which has about 150M tokens, the deduped Pile is split into 20 files, each of which (e.g. 00.jsonl) has about 10B tokens. To train for a greater number of epochs, we have to be able to use jsonl files with less number of tokens. 

@haileyschoelkopf I don't know how shuffled the deduped Pile is. It was split into 20 files, which isn't a large number, so I assume it's safe to say that 00.jsonl is sufficiently representative. If not, we will notice that there is a big gap between 1 epoch training and 64 epoch training, which wasn't the case for C4.

**Comment by haileyschoelkopf** [comment]
@AranKomat I see, makes sense that if there's not much gap it's probably representative! It's probably worth checking in on what's actually in those files though still and that the ordering isn't weird post-deduplication somehow...

**Comment by lintangsutawika** [comment]
Found a way to split.
```
cd /fsx/improved-t5/pile/
split -l 73268 --suffix-length=3 -d /fsx/pile_raw_deduped/dedupe0.87/train/00.jsonl
for f in x*; do mv -- "$f" "00_${f%}.jsonl"; done
```

**Comment by lintangsutawika** [comment]
Looks like we can close this isssue?
