### ISSUE TITLE
Shuffle the deduped Pile

### ISSUE THREAD

**Issue by lintangsutawika** [EleutherAI/architecture-objective#27]

**Comment by lintangsutawika** [comment]
@AranKomat We also want this to be a list of separate tasks for the memorization experiments, right?

**Comment by AranKomat** [comment]
Yeah. Once we shuffle Pile, we can just take one piece out of it, split it into many smaller pieces and use them for memorization experiments.

**Comment by lintangsutawika** [comment]
Since the Pile file parts are all jsonl where 1 line is 1 sample, we can shuffle using `shuf`
```
shuf <input file> -o <output file>
```

**Comment by lintangsutawika** [comment]
PILE shuffled at 
```
/fsx/improved-t5/pile/shuffled_dedup_pile/
```

Split version for `00.jsonl` is at `/fsx/improved-t5/pile/shuffled_dedup_pile/split_shuffle_00/`

**Comment by AranKomat** [comment]
Thanks a lot! I'll close the issue :)
